### ISSUE TITLE
Problems when trying to re-rank

### ISSUE THREAD

**Issue by RaniRaven** [canjiali/PARADE#3]
While trying to re-rank via GPU (not TPU) I entagled OOM issues, it seems like the code assumes infinite memory, or maybe a tensor flow bug. I find it hard to believe you had access to TPU with a TeraByte of TPU memory ....
I had to change batch-size to 4 (!) in order that the code will not crash.
Several issues :
[1] Do you have this code for tensorflow 2 ? As most of things here are depricated, and there are a lot of issues. It seems like GPU is not handled correctly, many issues there, and the estimator is not working correctly either.
[2] Many things are not synchronized, like in the last part of the re-rank script what is the local-dir exactly ? How do I have access to this information ? What is it supposed to be (as all of it is not documented) ?
[3] All the models you give here, do not contain the necessary parameters for running, so I had to combine from several places. The pre-trained model do not contain the config json file, and do not contain the vocabulary which is needed.

**Comment by andrewyates** [comment]
I can help with some of these points before @canjiali provides additional details.
- this TFv1 code was run on a single TPU v3-8. You will need a smaller batch size when using a GPU with less memory
- we have a [TFv2 implementation in the Capreolus toolkit](https://github.com/capreolus-ir/capreolus/blob/master/docs/reproduction/PARADE.md), which has been tested with a high-memory GPU (Quadro RTX 8000)
- Capreolus recently added a PyTorch implementation with AMP support, which reduces memory usage but still cannot fit on a single GPU. If you're interested in using this, let me know and I'll add a PyTorch version of the above guide to the repo
- the models here are fine-tuned versions of BERT/ELECTRA models, so of course the config and vocab file are unchanged. If you are using the HuggingFace Transformers library, we also provide the BERT/ELECTRA base models via the HGF modelhub. See [these lines in the Capreolus impl](https://github.com/capreolus-ir/capreolus/blob/bf5042354bd654cfd1f93f534c62e4a170048ee2/capreolus/reranker/parade.py#L16) for the names and [this Capreolus config file](https://github.com/capreolus-ir/capreolus/blob/master/docs/reproduction/config_parade.txt) for other config details

**Comment by canjiali** [comment]
@RaniRaven thanks for your interest in PARADE.

[1] Are you using TF 2 to run the code? I've tested the code using GPU and it works fine. which issues did you have?
[2] local-dir is a path to store the result locally so that you can evaluate the result using trec_eval. When running on TPU, the result file is stored on Google Cloud Storage (corresponding to *gs_dir*). qrels_path is where your TREC qrels file being stored.
[3] I've uploaded the config files and the vocabulary file. You should be able to download them at [link](https://zenodo.org/record/4302803/files/config.tar.gz?download=1). Sorry for the inconvenience. 

To test the code quickly, I'd recommend using the smaller BERT models first to get everything work! We also have the TF2 support in Capreolus as @andrewyates pointed out.

**Comment by RaniRaven** [comment]
Thank you both for your answers. Some of the things are clearer now.
I just find it peculiar that using the Electra Model is possible on a GPU only when using batch size of 2 or 4. I had to get that low in order to do it. And it seems like it runs forever, in half a day on P100, K80 or even V100 it didn't even finish the first folder on training.
Even a 2 GPU machine doesn't solve this issue, because the amount of GPU memory is per GPU, at least in those I used.
I'll try any code of TFv2 if it reduces the memory signature.  Cause the code is throwing a lot of deprecation warnings.
Are those tpu also available in the google cloud when creating an account there, or is it only available for "business type" ?
I was already able to find the config file somewhere else.
2 more interesting issues are :
[1] Is there some sample of using the resulting trained model through the huggingface libraries ? It seems like each one produces his own version of the modeling.py, and trying to use the models for getting word-embedding or sentence embedding in a known protocol is not available. If you have some sample, please show me.
[2] Does the code know to look for a saved checkpoint if it fails for some reason ?

Regards,
Rani

**Comment by canjiali** [comment]
batch size of 2 or 4 is normal for GPU. It takes 2.5 training hours for one fold on a TPU v3.8, while it can be as 20x slower on a GPU. You can also try the free TPU 2.8 on google colab (might be 2x slower than v3.8).
[1] No, I don't have one. isn't it simply loading the model and do whatever you want?
[2] tf estimator will load the latest checkpoint automatically.

**Comment by RaniRaven** [comment]
I understand now, that I was probably wrong in my estimation.
It seems like the process in never ending even for one fold. Just to make it straight, for the tuning of the model, how many documents are being used per query ? Cause I am trying something for a goal of AP@1000, it seems that the model never finish even for one fold.
For Robust, it is on model.ckpt-217000, after about 72 hours of working on a P100 GPU, and keeps on working. Now for all Robust, for 1000 documents per query there are about 140K documents, so in division to 5 folders, and multiplying by 16, it seems like it will take more than a week for training on a single folder ?
Will smaller model make any change ? or do I have to change for something like 20 documents per query for the tuning part ?
I still cannot understand how is it that TPU is that faster than GPU ?

**Comment by canjiali** [comment]
IIRC, using a batch size of 32 results in ~18k training steps for robust04 so using a batch size of 4 might give you ~144k training steps.
@andrewyates the early stopping mechanism and PyTorch AMP reduce the time to less than 36 hours per fold in the Capreolus repo. is it correct? @RaniRaven you can try that for a speedup.
sure, smaller models give you a huge speedup while reducing the effectiveness slightly... you can check table 3 in the paper for a reference.

**Comment by RaniRaven** [comment]
I'm sorry for the questions , but :
Does the amount of documents per query has any effect on the training length ?

**Comment by canjiali** [comment]
yes, you can check how the number of training steps is defined here: https://github.com/canjiali/PARADE/blob/master/run_reranking.py#L359

**Comment by RaniRaven** [comment]
O.k., I see that with smaller model it is working much faster. Meaning. I took the BERT-mini one, and it really improved the time a lot.
